# Generated by Django 5.2.3 on 2025-06-23 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Customer', '0001_initial'),
        ('App_Inventory', '0001_initial'),
        ('App_Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'รอดำเนินการ'), ('PROCESSING', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสิ้น'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Customer.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวน')),
                ('unit_price', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='ราคาต่อหน่วย (ณ วันที่สั่ง)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_details', to='App_Products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='App_OrderingProductForSale.orderrequest')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('invoice_type', models.CharField(choices=[('REGULAR', 'ใบเสร็จรับเงิน'), ('TAX', 'ใบกำกับภาษี')], default='TAX', max_length=10)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='ยอดรวมก่อนส่วนลด')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ส่วนลด (บาท)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='ยอดหลังหักส่วนลด')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=7.0, max_digits=5, verbose_name='อัตราภาษี (%)')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='ภาษีมูลค่าเพิ่ม')),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='ยอดรวมสุทธิ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('order_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='App_OrderingProductForSale.orderrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'รอจัดสินค้า'), ('PICKING', 'กำลังจัดสินค้า'), ('COMPLETED', 'จัดสินค้าเสร็จสิ้น')], default='PENDING', max_length=20, verbose_name='สถานะ')),
                ('order_request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='picking_order', to='App_OrderingProductForSale.orderrequest')),
                ('picker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้จัด')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PickingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_detail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='picking_detail', to='App_OrderingProductForSale.orderdetail')),
                ('picked_items', models.ManyToManyField(blank=True, help_text='Serial Number ของสินค้าที่ถูกจัด', to='App_Inventory.inventoryitem')),
                ('picking_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='App_OrderingProductForSale.pickingorder')),
            ],
        ),
    ]
