databases:
  - name: storems-db
    databaseName: storems
    user: storems

services:
  - type: web
    name: storems
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Storems.wsgi:application"
    plan: starter
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: storems-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: False
      - key: DJANGO_SETTINGS_MODULE
        value: Storems.settings
