# Generated by Django 5.2.3 on 2025-06-23 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Supplier', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='notes',
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='เลขที่บัญชีธนาคาร'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='bank_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='ชื่อธนาคาร'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('manufacturer', 'ผู้ผลิต'), ('distributor', 'ผู้จัดจำหน่าย'), ('service', 'ผู้ให้บริการ')], default='distributor', max_length=20, verbose_name='ประเภท'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(default='กรุงเทพฯ', max_length=100, verbose_name='เมือง/เขต'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='ตำแหน่งผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='country',
            field=models.CharField(default='ไทย', max_length=100, verbose_name='ประเทศ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='วงเงินเครดิต'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True, verbose_name='อีเมล'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='fax_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เบอร์แฟกซ์'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone_number',
            field=models.CharField(default='', max_length=30, verbose_name='เบอร์โทรศัพท์'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='postal_code',
            field=models.CharField(default='10000', max_length=20, verbose_name='รหัสไปรษณีย์'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(default='กรุงเทพมหานคร', max_length=100, verbose_name='จังหวัด'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='รหัสซัพพลายเออร์'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='เว็บไซต์'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(default='', verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(max_length=200, verbose_name='ชื่อบริษัท'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='ชื่อผู้ติดต่อ'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='เงื่อนไขการชำระเงิน'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='เลขประจำตัวผู้เสียภาษี'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.CreateModel(
            name='ContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('contact_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ติดต่อ')),
                ('contact_type', models.CharField(choices=[('phone', 'โทรศัพท์'), ('email', 'อีเมล'), ('meeting', 'ประชุม'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทการติดต่อ')),
                ('notes', models.TextField(verbose_name='บันทึก')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='บันทึกโดย')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_histories', to='App_Supplier.supplier', verbose_name='ซัพพลายเออร์')),
            ],
            options={
                'verbose_name': 'ประวัติการติดต่อ',
                'verbose_name_plural': 'ประวัติการติดต่อ',
                'ordering': ['-contact_date'],
            },
        ),
    ]
