# Generated by Django 5.2.3 on 2025-06-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อแบรนด์')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('brand_code', models.CharField(default='0000', help_text='รหัสแบรนด์ 4 หลัก', max_length=4, unique=True, verbose_name='รหัสแบรนด์')),
            ],
            options={
                'verbose_name': 'แบรนด์สินค้า',
                'verbose_name_plural': 'แบรนด์สินค้า',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อหมวดหมู่')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('category_code', models.CharField(default='000', help_text='รหัสหมวดหมู่ 3 หลัก', max_length=3, unique=True, verbose_name='รหัสหมวดหมู่')),
            ],
            options={
                'verbose_name': 'หมวดหมู่สินค้า',
                'verbose_name_plural': 'หมวดหมู่สินค้า',
            },
        ),
        migrations.CreateModel(
            name='SKUCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('unit', models.CharField(max_length=50, verbose_name='หน่วยนับ')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาทุน')),
                ('price_a', models.DecimalField(decimal_places=2, default=0, help_text='ราคาขายสำหรับลูกค้าทั่วไป', max_digits=10, verbose_name='ราคาขาย A')),
                ('price_aa', models.DecimalField(decimal_places=2, default=0, help_text='ราคาขายสำหรับลูกค้าประจำ', max_digits=10, verbose_name='ราคาขาย AA')),
                ('price_aaa', models.DecimalField(decimal_places=2, default=0, help_text='ราคาขายสำหรับลูกค้า VIP', max_digits=10, verbose_name='ราคาขาย AAA')),
                ('reorder_point', models.PositiveIntegerField(default=0, help_text='จำนวนสินค้าคงเหลือที่ควรทำการสั่งซื้อเพิ่ม', verbose_name='จุดสั่งซื้อ (Reorder Point)')),
                ('reorder_quantity', models.PositiveIntegerField(default=0, help_text='จำนวนที่ควรสั่งซื้อเมื่อถึงจุดสั่งซื้อ', verbose_name='จำนวนสั่งซื้อที่แนะนำ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดต')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Products.brand', verbose_name='แบรนด์')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Products.category', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'สินค้า',
                'verbose_name_plural': 'สินค้าทั้งหมด',
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_a', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา A')),
                ('price_aa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา AA')),
                ('price_aaa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา AAA')),
                ('effective_date', models.DateField(verbose_name='วันที่เริ่มต้น')),
                ('end_date', models.DateField(verbose_name='วันที่สิ้นสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='App_Products.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'ราคาพิเศษ',
                'verbose_name_plural': 'ราคาพิเศษ',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วยจากซัพพลายเออร์')),
                ('minimum_order_quantity', models.PositiveIntegerField(default=1, verbose_name='จำนวนสั่งซื้อขั้นต่ำ')),
                ('is_primary_supplier', models.BooleanField(default=False, verbose_name='ซัพพลายเออร์หลัก')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='App_Products.product', verbose_name='สินค้า')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='App_Supplier.supplier', verbose_name='ซัพพลายเออร์')),
            ],
            options={
                'verbose_name': 'ซัพพลายเออร์ของสินค้า',
                'verbose_name_plural': 'ซัพพลายเออร์ของสินค้า',
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='App_Product_sku_e1ae2f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='App_Product_name_321a7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productsupplier',
            unique_together={('product', 'supplier')},
        ),
    ]
