# Generated by Django 5.2.3 on 2025-06-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skucounter',
            options={'verbose_name': 'ตัวนับ SKU', 'verbose_name_plural': 'ตัวนับ SKU'},
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='รหัสสินค้าเฉพาะ จะถูกสร้างอัตโนมัติหากไม่ระบุ (รูปแบบ: หมวดหมู่-แบรนด์-ปี-ลำดับ)', max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
