# Generated by Django 5.2.3 on 2025-06-23 14:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ระบุชื่อแผนกให้ชัดเจน เช่น 'ฝ่ายบุคคล', 'ฝ่ายบัญชี'", max_length=100, verbose_name='ชื่อแผนก')),
                ('description', models.TextField(blank=True, help_text='อธิบายรายละเอียดของแผนก หน้าที่ความรับผิดชอบ', null=True, verbose_name='คำอธิบายแผนก')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'แผนก',
                'verbose_name_plural': 'แผนก',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="ระบุชื่อตำแหน่งงานให้ชัดเจน เช่น 'ผู้จัดการฝ่ายบุคคล', 'พนักงานบัญชี'", max_length=100, verbose_name='ชื่อตำแหน่ง')),
                ('description', models.TextField(blank=True, help_text='อธิบายรายละเอียดของตำแหน่งงาน หน้าที่ความรับผิดชอบ', null=True, verbose_name='คำอธิบายตำแหน่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('department', models.ForeignKey(help_text='เลือกแผนกที่ตำแหน่งงานนี้สังกัด', on_delete=django.db.models.deletion.CASCADE, to='App_Accounts.department', verbose_name='แผนก')),
            ],
            options={
                'verbose_name': 'ตำแหน่ง',
                'verbose_name_plural': 'ตำแหน่ง',
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('employee_id', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='รหัสพนักงาน')),
                ('date_of_birth', models.DateField(blank=True, help_text='คลิกที่ไอคอนปฏิทินเพื่อเลือกวันที่', null=True, verbose_name='วันเดือนปีเกิด')),
                ('gender', models.CharField(blank=True, help_text='ระบุเพศของพนักงาน', max_length=10, null=True, verbose_name='เพศ')),
                ('nationality', models.CharField(blank=True, help_text='ระบุสัญชาติของพนักงาน', max_length=50, null=True, verbose_name='สัญชาติ')),
                ('phone_number', models.CharField(blank=True, help_text='ระบุเบอร์โทรศัพท์ที่ติดต่อได้', max_length=15, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.TextField(blank=True, help_text='ระบุที่อยู่ปัจจุบันที่สามารถติดต่อได้', null=True, verbose_name='ที่อยู่')),
                ('emergency_contact', models.CharField(blank=True, help_text='ระบุเบอร์โทรศัพท์สำหรับติดต่อในกรณีฉุกเฉิน', max_length=15, null=True, verbose_name='เบอร์ติดต่อฉุกเฉิน')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='รูปโปรไฟล์')),
                ('date_of_joining', models.DateField(blank=True, help_text='คลิกที่ไอคอนปฏิทินเพื่อเลือกวันที่เริ่มงาน', null=True, verbose_name='วันที่เริ่มงาน')),
                ('employment_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract')], default='FT', help_text='เลือกประเภทการจ้างงานของพนักงาน', max_length=2, verbose_name='ประเภทการจ้างงาน')),
                ('login_attempts', models.IntegerField(default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='หัวหน้างาน')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App_Accounts.position', verbose_name='ตำแหน่ง')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'พนักงาน',
                'verbose_name_plural': 'พนักงาน',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to=settings.AUTH_USER_MODEL, verbose_name='หัวหน้าแผนก'),
        ),
    ]
