# Generated by Django 5.2.3 on 2025-06-23 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Products', '0001_initial'),
        ('App_Supplier', '0002_remove_supplier_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PRCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('po_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='เลขที่ใบสั่งซื้อ')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่สั่งซื้อ')),
                ('expected_delivery_date', models.DateField(verbose_name='วันที่คาดว่าจะได้รับ')),
                ('status', models.CharField(choices=[('draft', 'ร่าง'), ('pending_approval', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว (รอรับของ)'), ('partially_received', 'รับของบางส่วนแล้ว'), ('fully_received', 'รับของครบแล้ว'), ('rejected', 'ไม่อนุมัติ'), ('cancelled', 'ยกเลิก')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='App_Supplier.supplier', verbose_name='ผู้ขาย')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่รับของ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับของ')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='App_Purchase.purchaseorder', verbose_name='ใบสั่งซื้อ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวนสั่งซื้อ')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดรวม')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Products.product', verbose_name='สินค้า')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='App_Purchase.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(verbose_name='จำนวนที่รับ')),
                ('condition', models.CharField(choices=[('good', 'สภาพดี'), ('damaged', 'เสียหาย'), ('incorrect', 'ไม่ตรงตามสั่ง')], default='good', max_length=20, verbose_name='สภาพสินค้า')),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='App_Purchase.goodsreceipt')),
                ('purchase_order_detail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_details', to='App_Purchase.purchaseorderdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pr_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='เลขที่ใบขอซื้อ')),
                ('department', models.CharField(max_length=100, verbose_name='แผนก')),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ขอซื้อ')),
                ('required_date', models.DateField(verbose_name='วันที่ต้องการใช้งาน')),
                ('status', models.CharField(choices=[('draft', 'ฉบับร่าง'), ('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ไม่อนุมัติ'), ('cancelled', 'ยกเลิก'), ('converted', 'แปลงเป็น PO แล้ว')], default='draft', max_length=20, verbose_name='สถานะ')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอซื้อ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='purchase_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='App_Purchase.purchaserequisition', verbose_name='อ้างอิงใบขอซื้อ'),
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='จำนวน')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Products.product', verbose_name='สินค้า')),
                ('purchase_requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='App_Purchase.purchaserequisition')),
            ],
        ),
    ]
