# Generated by Django 5.2.3 on 2025-06-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=20, unique=True, verbose_name='รหัสลูกค้า')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'บุคคลธรรมดา'), ('COMPANY', 'นิติบุคคล')], default='INDIVIDUAL', max_length=20, verbose_name='ประเภทลูกค้า')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อลูกค้า/บริษัท')),
                ('tax_id', models.CharField(blank=True, max_length=13, null=True, verbose_name='เลขประจำตัวผู้เสียภาษี')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทรศัพท์')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='จังหวัด')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='รหัสไปรษณีย์')),
                ('price_tier', models.CharField(choices=[('A', 'ราคา A'), ('AA', 'ราคา AA'), ('AAA', 'ราคา AAA')], default='A', max_length=3, verbose_name='ระดับราคา')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='วงเงินเครดิต')),
                ('credit_term', models.IntegerField(default=0, verbose_name='เครดิตเทอม (วัน)')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะการใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่อัปเดตล่าสุด')),
            ],
            options={
                'verbose_name': 'ลูกค้า',
                'verbose_name_plural': 'ลูกค้า',
                'ordering': ['name'],
            },
        ),
    ]
