# Generated by Django 5.2.3 on 2025-06-25 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Customer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='province',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_active',
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขที่บัญชี'),
        ),
        migrations.AddField(
            model_name='customer',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อธนาคาร'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เมือง/อำเภอ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_name',
            field=models.CharField(default='', max_length=100, verbose_name='ชื่อผู้ติดต่อ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='ไทย', max_length=100, verbose_name='ประเทศ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='รหัสลูกค้า'),
        ),
        migrations.AddField(
            model_name='customer',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์แฟกซ์'),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เงื่อนไขการชำระเงิน'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('active', 'ใช้งาน'), ('inactive', 'หยุดใช้งาน'), ('suspended', 'ระงับการใช้งาน')], default='active', max_length=20, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='เว็บไซต์'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'บุคคลธรรมดา'), ('company', 'นิติบุคคล')], default='individual', max_length=20, verbose_name='ประเภทลูกค้า'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อลูกค้า/บริษัท'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.CreateModel(
            name='CustomerContactHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('contact_type', models.CharField(choices=[('phone', 'โทรศัพท์'), ('email', 'อีเมล'), ('meeting', 'ประชุม'), ('visit', 'เยี่ยมชม'), ('other', 'อื่นๆ')], max_length=20, verbose_name='ประเภทการติดต่อ')),
                ('contact_date', models.DateTimeField(verbose_name='วันที่ติดต่อ')),
                ('subject', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('description', models.TextField(verbose_name='รายละเอียด')),
                ('contacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ติดต่อ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_histories', to='App_Customer.customer', verbose_name='ลูกค้า')),
            ],
            options={
                'verbose_name': 'ประวัติการติดต่อลูกค้า',
                'verbose_name_plural': 'ประวัติการติดต่อลูกค้า',
                'ordering': ['-contact_date'],
            },
        ),
    ]
