# Generated by Django 5.2.3 on 2025-06-23 15:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('serial_number', models.CharField(blank=True, help_text='Base62 serial number, auto-generated', max_length=10, unique=True)),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='Lot/Batch Number')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('reserved', 'จองแล้ว'), ('sold', 'ขายแล้ว'), ('damaged', 'เสียหาย'), ('expired', 'หมดอายุ')], default='available', max_length=20, verbose_name='สถานะ')),
                ('received_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับเข้า')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='วันที่หมดอายุ')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='สร้างโดย')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Products.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'สินค้าในคลัง (รายชิ้น)',
                'verbose_name_plural': 'สินค้าในคลัง (รายชิ้น)',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('location_code', models.CharField(max_length=50, unique=True, verbose_name='รหัสตำแหน่ง')),
                ('location_name', models.CharField(max_length=100, verbose_name='ชื่อตำแหน่ง')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
            ],
            options={
                'verbose_name': 'ตำแหน่งจัดเก็บ',
                'verbose_name_plural': 'ตำแหน่งจัดเก็บทั้งหมด',
                'ordering': ['location_code'],
            },
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_date', models.DateTimeField(verbose_name='วันที่ย้าย')),
                ('reason', models.TextField(blank=True, verbose_name='เหตุผล')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ประวัติการย้ายตำแหน่ง',
                'verbose_name_plural': 'ประวัติการย้ายตำแหน่ง',
                'ordering': ['-move_date'],
            },
        ),
        migrations.CreateModel(
            name='SerialCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('count_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='วันที่ตรวจนับ')),
                ('status', models.CharField(choices=[('in_progress', 'กำลังดำเนินการ'), ('completed', 'เสร็จสิ้น'), ('cancelled', 'ยกเลิก')], default='in_progress', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'การตรวจนับสต็อก',
                'verbose_name_plural': 'การตรวจนับสต็อก',
                'ordering': ['-count_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_serial_number', models.CharField(blank=True, help_text="Serial ที่นับเจอ (กรณี 'เกิน')", max_length=100)),
                ('status', models.CharField(choices=[('found', 'พบ'), ('missing', 'ไม่พบ'), ('extra', 'เกิน')], max_length=20, verbose_name='ผลการนับ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
            ],
            options={
                'verbose_name': 'รายการตรวจนับ',
                'verbose_name_plural': 'รายการตรวจนับ',
            },
        ),
        migrations.CreateModel(
            name='DamagedItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('inventory_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='damage_record', serialize=False, to='App_Inventory.inventoryitem', verbose_name='สินค้าที่เสียหาย')),
                ('damage_date', models.DateField(verbose_name='วันที่พบความเสียหาย')),
                ('damage_description', models.TextField(verbose_name='รายละเอียดความเสียหาย')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('repaired', 'ซ่อมแซมแล้ว'), ('written_off', 'ตัดจำหน่าย')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='ค่าซ่อมแซม')),
                ('action_date', models.DateField(blank=True, null=True, verbose_name='วันที่ดำเนินการ (ซ่อม/ตัดจำหน่าย)')),
                ('action_note', models.TextField(blank=True, null=True, verbose_name='บันทึกการดำเนินการ')),
            ],
            options={
                'verbose_name': 'รายการสินค้าเสียหาย',
                'verbose_name_plural': 'รายการสินค้าเสียหาย',
                'ordering': ['-damage_date'],
            },
        ),
    ]
