# Generated by Django 5.2.3 on 2025-06-23 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('App_Inventory', '0001_initial'),
        ('App_OrderingProductForSale', '0001_initial'),
        ('App_Products', '0001_initial'),
        ('App_Purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='receipt_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='App_Purchase.goodsreceiptdetail', verbose_name='รายละเอียดการรับเข้า'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='sales_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='App_OrderingProductForSale.orderdetail', verbose_name='รายละเอียดการขาย'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Inventory.location', verbose_name='ตำแหน่งจัดเก็บ'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_moves', to='App_Inventory.location', verbose_name='จากตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='inventory_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='App_Inventory.inventoryitem', verbose_name='สินค้า'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='moved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ย้ายโดย'),
        ),
        migrations.AddField(
            model_name='locationhistory',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_moves', to='App_Inventory.location', verbose_name='ไปยังตำแหน่ง'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='counted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตรวจนับ'),
        ),
        migrations.AddField(
            model_name='stockcount',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App_Inventory.location', verbose_name='ตำแหน่งที่นับ'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Inventory.inventoryitem', verbose_name='สินค้าในระบบ'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='App_Products.product', verbose_name='สินค้าที่พบ'),
        ),
        migrations.AddField(
            model_name='stockcountitem',
            name='stock_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='App_Inventory.stockcount', verbose_name='ชุดการตรวจนับ'),
        ),
        migrations.AddField(
            model_name='damageditem',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['product', 'status'], name='App_Invento_product_5d94d0_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['serial_number'], name='App_Invento_serial__60701e_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryitem',
            index=models.Index(fields=['lot_number'], name='App_Invento_lot_num_155272_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stockcountitem',
            unique_together={('stock_count', 'inventory_item')},
        ),
    ]
